---
title: "BDNS"
---

# Building Device and Asset Naming Standards initiative

Status: *release* {{< var tag >}}

This repository holds resources for an initiative to improve interoperability in building management, by focusing on standardising naming of building devices and assets.

Achieving a common standard across building devices’ naming is an important first step towards being able to efficiently collect, analyse and capture data insights from buildings, and thus optimise building performance to reduce the operational cost and environmental impact of managing buildings.

Longer-term, this sets the groundwork for real industry collaboration - with the potential to create industry-wide benchmarking, and to facilitate trading of buildings between portfolios.

A naming and labelling standard (complementing other industry initiatives ) will simplify and drive consistency, thus increasing value by unlocking the application of technologies such as machine learning.  

The work of this community group aligns with and complements other initiatives in the industry such as:

* [IFC](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/)
* [Uniclass](https://www.thenbs.com/our-tools/uniclass-2015) and [Uniclass2](http://www.cpic.org.uk/uniclass2/)
* [Omniclass](https://www.csiresources.org/standards/omniclass)
* [CIBSE Symbols](https://www.cibse.org/knowledge/digital-knowledge-tools/symbols)
* [UDMI](https://github.com/faucetsdn/udmi)
* [Web of Things](https://www.w3.org/WoT/)
* [HyperCat](https://hypercatiot.github.io/)
* [Project Haystack](https://project-haystack.org/)
* [Brick Schema](https://brickschema.org/)
* [Digital Buildings Ontology](https://github.com/google/digitalbuildings)

In scope for this work are:
- A [specification for naming syntax](BDNS_Specification_naming_syntax.md)
- A [register of building device type abbreviations](BDNS_Abbreviations_Register.csv)

The [register of building device type abbreviations](BDNS_Abbreviations_Register.csv) includes the following columns:

* `asset_description` - a desription of what is named; the description typically includes a category when the level of granularity of the abbreviation is more specific
* `asset_abbreviation` - the BDNS abbreviation itself
* `can_be_connected` - a boolean value that distinguishes between assets that do not include any means of network connectivity and connectable devices
* `dbo_entity_type` - the [Digital Buildings Ontology](https://github.com/google/digitalbuildings) namespace and entity type that can be associated to the BDNS abbreviation; NOTE: while BDNS presupposes that modelers will apply abbreviations consistently based on similar domain expertise, DBO does not; instead, it provides definitions for devices which may have overlapping function or where terms are ambiguous. For example, while a BDNS user may find the distinction between AHU, ACU, and RTU to be meaningful, DBO does consider all of these as classes of AHU (and provides a definition for what an AHU is.
* `ifc_class` - the [IFC](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/) class that can be associated to the BDNS abbreviation
* `ifc_type` - the specific [IFC](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/) type associated to the IFC class that can be associated to the BDNS abbreviation

The comparison columns have the purpose of providing a simple means to correlate the naming of instances with ontology objects that are present in different building services and systems related ontologies, like the [Digital Buildings Ontology](https://github.com/google/digitalbuildings) and [IFC](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/).


## Use

The device and asset names defined in this standard are meant to be used in the following applications:

* naming of CAD object instances in drawings
* naming of object instances in BIM models
* naming of control devices in control software (for instance BACnet device names)
* naming of assets in asset management systems
* naming of devices in IoT ingestion systems
* naming of devices and assets in databases
* naming of devices and assets in MQTT topics

## Past Versions

- Currently we only serve the latest version of the BDNS built website and pdf documents.
- The source markdown files of previous versions can be reviewed by referring to the appropriate Github tag/release.
  - e.g. [BDNS=1.2.0](https://github.com/theodi/BDNS/tree/1.2.0) = `https://github.com/theodi/BDNS/tree/1.2.0` for the source files of v1.2.0
  - e.g. [BDNS_Specification_naming_syntax=1.2.0](https://github.com/theodi/BDNS/blob/1.2.0/BDNS_Specification_naming_syntax.md) = `https://github.com/theodi/BDNS/blob/1.2.0/BDNS_Specification_naming_syntax.md` for a specific version of a document 
- The `BDNS_Abbreviations_Register.csv` data file can also be retrieved directly from a previous tag/release if you are required to pin to a given version.
  - e.g. [BDNS_Abbreviations_Register.csv=1.2.0](https://raw.githubusercontent.com/theodi/BDNS/1.2.0/BDNS_Abbreviations_Register.csv) = `https://raw.githubusercontent.com/theodi/BDNS/1.2.0/BDNS_Abbreviations_Register.csv`

## Note

The standard is primarily focusing on naming of building control devices, but with its growing usage it also includes a number of maintainable asset names and types.
