mindmap
  root((**Digital 
Transformation**))
    **New Services**
      Smart Buildings / Digital Twins
      Digital Commissioning
      Performance Monitoring
    **Automation**
      Efficiency
        More Profit
      Faster Outputs
        Improved Service
    **Real-time Monitoring**
      Easier to manage
    **Building a Growing Resource**
      More Automation
      Leverage AI
    **Standardisation**
      Data Insights
      Raising Minimum Standards
      Robust Design